name: flutter_infinite_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  http: ^0.12.0
  equatable: ^1.2.0
  url_launcher: ^5.4.10

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: OldStandardTT
      fonts:
        - asset: assets/fonts/OldStandardTT-Regular.ttf
        - asset: assets/fonts/OldStandardTT-Italic.ttf
        - asset: assets/fonts/OldStandardTT-Bold.ttf
      
  uses-material-design: true